// src/lib/csvImport.js
//
// Shared engine behind the "Import CSV" feature across three entity
// types: salon services, auto services, and retail stock/products (the
// last one shared by both business types via the `stock` table).
//
// Deliberately config-driven rather than three near-duplicate
// implementations -- the three entities differ only in table name,
// column shape, and which field types apply, all expressed as data
// below rather than branching logic.
//
// papaparse is dynamically imported (not a static import) so its ~17KB
// only loads when someone actually opens the import modal, not on every
// page load of Services/Inventory.

import { db } from "./db.js";

// ---------------------------------------------------------------------
// Entity configs
// ---------------------------------------------------------------------
// Each config describes one importable entity:
//   table        - the Supabase table to write to (must be in
//                  db.js's TENANT_TABLES so salon_id is auto-injected)
//   templateName - filename for the downloadable template
//   columns      - ordered list of { key, header, required, type }
//                  key    = field name in the row object we build
//                  header = expected CSV column header (case-insensitive)
//                  type   = "text" | "number"
//   matchField   - which built row field is used to detect an existing
//                  row for this salon (case-insensitive, trimmed)
//   buildRow(fields) - turns validated { key: value } into the exact
//                  object shape the table expects (handles renames like
//                  category -> cat, and any fields the table needs that
//                  aren't user-supplied, like a generated id)
export const SALON_SERVICES_CONFIG = {
  table: "services",
  templateName: "trimora-services-template.csv",
  columns: [
    { key: "name", header: "name", required: true, type: "text" },
    { key: "category", header: "category", required: true, type: "text" },
    { key: "price", header: "price", required: true, type: "number" },
  ],
  matchField: "name",
  buildRow: function (f) {
    return { name: f.name, cat: f.category, price: f.price, active: true };
  },
  // PATCH payload when updating an existing match -- deliberately
  // narrower than buildRow's POST shape (never flips active on update;
  // that's what the existing Remove/Activate buttons are for).
  buildUpdate: function (f) {
    return { name: f.name, cat: f.category, price: f.price };
  },
};

export const AUTO_SERVICES_CONFIG = {
  table: "auto_services",
  templateName: "trimora-auto-services-template.csv",
  columns: [
    { key: "name", header: "name", required: true, type: "text" },
    { key: "description", header: "description", required: false, type: "text" },
    { key: "duration_minutes", header: "duration_minutes", required: false, type: "number" },
    { key: "price", header: "price", required: true, type: "number" },
  ],
  matchField: "name",
  buildRow: function (f) {
    return {
      name: f.name,
      description: f.description || null,
      duration_minutes: f.duration_minutes || null,
      price: f.price,
      active: true,
    };
  },
  buildUpdate: function (f) {
    return {
      name: f.name,
      description: f.description || null,
      duration_minutes: f.duration_minutes || null,
      price: f.price,
    };
  },
};

// Shared by both business types -- salon retail products and Auto
// parts/consumables are the same `stock` table (see auto/ServicesPage.jsx's
// existing comment on this). Category is free text here (unlike the
// manual Add Product form's fixed Hair/Nails/Beauty/Spa dropdown),
// since Auto parts don't fit those categories at all.
export const STOCK_CONFIG = {
  table: "stock",
  templateName: "trimora-products-template.csv",
  columns: [
    { key: "name", header: "name", required: true, type: "text" },
    { key: "category", header: "category", required: true, type: "text" },
    { key: "price", header: "price", required: true, type: "number" },
    { key: "stock_qty", header: "stock_qty", required: true, type: "number" },
  ],
  matchField: "name",
  buildRow: function (f, index) {
    // stock.id is a text primary key, not auto-generated by Postgres --
    // matches InventoryView.jsx's existing "PRD" + Date.now() convention,
    // with an index suffix since a bulk import can create many rows
    // within the same millisecond (Date.now() alone could collide).
    return {
      id: "PRD" + Date.now() + "-" + index,
      name: f.name,
      cat: f.category,
      price: f.price,
      stock: f.stock_qty,
    };
  },
  buildUpdate: function (f) {
    return { name: f.name, cat: f.category, price: f.price, stock: f.stock_qty };
  },
};

// ---------------------------------------------------------------------
// Template download
// ---------------------------------------------------------------------
export function downloadTemplate(config) {
  var header = config.columns.map(function (c) { return c.header; }).join(",");
  var blob = new Blob([header + "\n"], { type: "text/csv;charset=utf-8;" });
  var url = URL.createObjectURL(blob);
  var a = document.createElement("a");
  a.href = url;
  a.download = config.templateName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------
// Parse + validate
// ---------------------------------------------------------------------
// Returns { rows, parseError }. rows is always an array (empty if
// parseError is set). Each row:
//   { line, status: "new"|"update"|"error", fields, errors, matchId }
export async function parseAndValidate(file, config, existingRows) {
  var Papa;
  try {
    Papa = (await import("papaparse")).default;
  } catch (e) {
    return { rows: [], parseError: "Couldn't load the CSV parser. Check your connection and try again." };
  }

  var parsed = await new Promise(function (resolve) {
    Papa.parse(file, {
      header: true,
      skipEmptyLines: true,
      transformHeader: function (h) { return h.trim().toLowerCase(); },
      complete: resolve,
      error: function (err) { resolve({ data: [], errors: [{ message: err.message }] }); },
    });
  });

  if (!parsed.data || parsed.data.length === 0) {
    return { rows: [], parseError: "No rows found in that file. Check it matches the template." };
  }

  // Build a case-insensitive, trimmed name -> id lookup for existing rows.
  var existingByName = {};
  (existingRows || []).forEach(function (r) {
    var key = String(r[config.matchField] || "").trim().toLowerCase();
    if (key) existingByName[key] = r.id;
  });

  var rows = parsed.data.map(function (raw, i) {
    var fields = {};
    var errors = [];

    config.columns.forEach(function (col) {
      var raw_val = raw[col.header];
      var val = raw_val == null ? "" : String(raw_val).trim();

      if (!val) {
        if (col.required) errors.push(col.header + " is required");
        fields[col.key] = col.type === "number" ? null : "";
        return;
      }

      if (col.type === "number") {
        var num = Number(val);
        if (!isFinite(num)) {
          errors.push(col.header + " must be a number (got \"" + val + "\")");
          fields[col.key] = null;
        } else {
          fields[col.key] = num;
        }
      } else {
        fields[col.key] = val;
      }
    });

    var matchId = null;
    if (fields.name) {
      var key = String(fields.name).trim().toLowerCase();
      if (existingByName.hasOwnProperty(key)) matchId = existingByName[key];
    }

    return {
      line: i + 2, // +1 for 0-index, +1 for the header row
      status: errors.length > 0 ? "error" : (matchId ? "update" : "new"),
      fields: fields,
      errors: errors,
      matchId: matchId,
    };
  });

  return { rows: rows, parseError: null };
}

// ---------------------------------------------------------------------
// Commit
// ---------------------------------------------------------------------
// Takes the validated rows (only "new"/"update" ones are acted on) and
// writes them. New rows go in a single batch POST (db.js already
// supports an array body and stamps salon_id on every row). Updates go
// one PATCH at a time -- PostgREST/db.js's PATCH here targets one
// ?id=eq.X filter per call, and updates are expected to be the minority
// case, not the bulk case.
export async function commitImport(config, validatedRows) {
  var newRows = validatedRows.filter(function (r) { return r.status === "new"; });
  var updateRows = validatedRows.filter(function (r) { return r.status === "update"; });

  var createdCount = 0;
  var updatedCount = 0;
  var failedLines = [];

  if (newRows.length > 0) {
    var payload = newRows.map(function (r, i) { return config.buildRow(r.fields, i); });
    var saved = await db("POST", config.table, payload);
    if (saved && Array.isArray(saved)) {
      createdCount = saved.length;
    } else {
      newRows.forEach(function (r) { failedLines.push(r.line); });
    }
  }

  for (var i = 0; i < updateRows.length; i++) {
    var r = updateRows[i];
    var ok = await db("PATCH", config.table, config.buildUpdate(r.fields), "?id=eq." + r.matchId);
    if (ok) {
      updatedCount++;
    } else {
      failedLines.push(r.line);
    }
  }

  return { createdCount: createdCount, updatedCount: updatedCount, failedLines: failedLines };
}
