-- Per-payment secret used to verify mpesa-callback actually corresponds to
-- a push this system initiated (audit Critical-2 -- M-Pesa payment
-- confirmation forgery). Previously, checkout_request_id -- which the
-- frontend legitimately receives for polling -- was also the only thing
-- mpesa-callback checked, and it required no proof of caller identity at
-- all. verify_jwt:true on the function doesn't help here: it only
-- requires *a* valid Supabase JWT, and the public anon key already
-- satisfies that.
--
-- callback_token is generated by mpesa-stk-push, embedded only in the
-- CallBackURL registered with Safaricom (?t=...), and never returned to
-- the frontend. mpesa-callback now requires it to match before
-- processing any update.
--
-- Applied directly to the live DB and verified 2026-07-14/15 via a SQL-
-- level simulation of both the forged (wrong token, correctly ignored)
-- and legitimate (correct token, correctly updates) paths against a
-- throwaway test row, cleaned up afterward. This file brings migration
-- history back in sync with prod.
--
-- Note: as of this migration, salon_mpesa_payments has zero real rows --
-- M-Pesa Go Live / till whitelisting appears to still be in progress, so
-- this change could not be verified against live Safaricom traffic.
-- Recommend an end-to-end sandbox/live test once Go Live is active.

ALTER TABLE public.salon_mpesa_payments
  ADD COLUMN callback_token text;
